// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/submitReviews.ts";
import * as $$$0 from "./loaders/productDetailsPage.ts";
import * as $$$$$$$$$1 from "./actions/sendImageReview.ts";
import * as $$$$$$$$$2 from "./actions/confirmSendImage.ts";

const manifest = {
  "loaders": {
    "konfidency/loaders/productDetailsPage.ts": $$$0,
  },
  "actions": {
    "konfidency/actions/submitReviews.ts": $$$$$$$$$0,
    "konfidency/actions/sendImageReview.ts": $$$$$$$$$1,
    "konfidency/actions/confirmSendImage.ts": $$$$$$$$$2,
  },
  "name": "konfidency",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
